name: postgres_dart_gdbc
description: A sample command-line application.
version: 0.0.6
repository: https://github.com/graph-cn/postgres_dart_gdbc

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  postgres: ^3.5.6
  dart_gdbc: ^0.0.6
  # dart_gdbc: 
  #   path: ../../
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
